# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

enableImmutableInstalls: false
enableInlineBuilds: false
enableTelemetry: false
httpTimeout: 60000
nodeLinker: node-modules
npmRegistryServer: "https://registry.yarnpkg.com"
checksumBehavior: update

# This will fix the build error with @lerna/legacy-package-management
# See https://github.com/lerna/repro/pull/11
packageExtensions:
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      "js-yaml": "*"
      "rimraf": "*"
    peerDependencies:
      "nx": "*"
  "@jupyterlab/metadataform@*":
    dependencies:
      "@rjsf/utils": "*"
  "@jupyter-widgets/jupyterlab-manager@*":
    peerDependencies:
      "react": "*"
  "@jupyter/collaboration-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/cell-toolbar-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/completer@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/console-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/csvviewer-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/documentsearch-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/filebrowser-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/fileeditor-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/mainmenu-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/markdownviewer-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/services@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/statusbar-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/toc-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/translation-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/server@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/settings@*":
    peerDependencies:
      "react": "*"
  "@storybook/addon-controls@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/manager-api@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@plotly/mapbox-gl@*":
    peerDependencies:
      "mapbox-gl": "*"
  "jupyterlab-plotly@*":
    peerDependencies:
      "mapbox-gl": "*"
      "react": "*"
  "@datalayer/primer-addons@*":
    peerDependencies:
      "react-is": "*"
      "@babel/core": "*"
  "plotly.js@*":
    peerDependencies:
      "mapbox-gl": "*"
  "babel-plugin-styled-components@*":
    peerDependencies:
      "@babel/core": "*"
  "styled-components@*":
    peerDependencies:
      "@babel/core": "*"
  "@jupyterlab/vega3-extension@*":
    peerDependencies:
      "vega": "*"
  "vega-embed@*":
    peerDependencies:
      "vega": "*"
  "@jupyterlab/json-extension@*":
    peerDependencies:
      "@types/react": "*"
  "@jupyter-widgets/base-manager@*":
    peerDependencies:
      "react": "*"
  "@jupyter-widgets/base@*":
    peerDependencies:
      "react": "*"
  "@jupyter/docprovider@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/application@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/console@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/logconsole@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/lsp@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/outputarea@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/rendermime@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/running-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/terminal@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/translation@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/contents@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/javascript-kernel-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/kernel@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/pyodide-kernel-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/server-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/session@*":
    peerDependencies:
      "react": "*"
  "@jupyter-widgets/controls@*":
    peerDependencies:
      "react": "*"
  "@jupyter-widgets/html-manager@*":
    peerDependencies:
      "react": "*"
  "@jupyter-widgets/output@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/attachments@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/javascript-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/launcher-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/markdownviewer@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/markedparser-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/mathjax-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/nbconvert-css@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/rendermime-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/testutils@*":
    peerDependencies:
      "react": "*"
      "typescript": "*"
  "@jupyterlab/theme-dark-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/theme-light-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/ui-components-extension@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/javascript-kernel@*":
    peerDependencies:
      "react": "*"
  "@jupyterlite/pyodide-kernel@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/codemirror@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/csvviewer@*":
    peerDependencies:
      "react": "*"
  "@jupyterlab/mainmenu@*":
    peerDependencies:
      "react": "*"
